# Miscelanneous Stuff in NumPy

In [1]:
import numpy as np

## Scalars

In [2]:
s = np.array(5)
s

array(5)

In [3]:
s.shape

()

In [4]:
x = s+3
x

8

In [5]:
type(x)

numpy.int64

In [6]:
x.shape

()

## Vectors

In [7]:
v = np.array([1, 2, 3])
v

array([1, 2, 3])

In [8]:
v.shape

(3,)

In [9]:
x = v[1]
x

2

In [10]:
v[1:]

array([2, 3])

## Matrices

In [11]:
m = np.array([[1,2,3], [4,5,6], [7,8,9]])
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
m.shape

(3, 3)

## Tensors

In [13]:
t = np.array([[[[1],[2]],[[3],[4]],[[5],[6]]],[[[7],[8]],\
    [[9],[10]],[[11],[12]]],[[[13],[14]],[[15],[16]],[[17],[18]]]])
t

array([[[[ 1],
         [ 2]],

        [[ 3],
         [ 4]],

        [[ 5],
         [ 6]]],


       [[[ 7],
         [ 8]],

        [[ 9],
         [10]],

        [[11],
         [12]]],


       [[[13],
         [14]],

        [[15],
         [16]],

        [[17],
         [18]]]])

In [14]:
t.shape

(3, 3, 2, 1)

In [15]:
t[0]

array([[[1],
        [2]],

       [[3],
        [4]],

       [[5],
        [6]]])

In [16]:
t[1]

array([[[ 7],
        [ 8]],

       [[ 9],
        [10]],

       [[11],
        [12]]])

In [17]:
t[2]

array([[[13],
        [14]],

       [[15],
        [16]],

       [[17],
        [18]]])

In [18]:
t[2][1][1][0]

16

## Changing Shapes

In [19]:
v = np.array([1,2,3,4])
v

array([1, 2, 3, 4])

In [20]:
v.shape

(4,)

In [21]:
x = v.reshape(1, 4)
x

array([[1, 2, 3, 4]])

In [22]:
x = v.reshape(4, 1)
x

array([[1],
       [2],
       [3],
       [4]])

In [23]:
x = v[None, :]
x

array([[1, 2, 3, 4]])

In [24]:
x = v[:, None]
x

array([[1],
       [2],
       [3],
       [4]])

## Element-wise Operations

In [25]:
values = [1,2,3,4,5]
values = np.array(values) + 5
values

array([ 6,  7,  8,  9, 10])

In [26]:
values+=5
values

array([11, 12, 13, 14, 15])

## Element-wise Matrix Operations

In [27]:
a = np.array([[1,3],[5,7]])
a

array([[1, 3],
       [5, 7]])

In [28]:
b = np.array([[2,4],[6,8]])
b

array([[2, 4],
       [6, 8]])

In [29]:
a+b

array([[ 3,  7],
       [11, 15]])

In [30]:
c = np.array([[2,3,6],[4,5,9],[1,8,7]])
c

array([[2, 3, 6],
       [4, 5, 9],
       [1, 8, 7]])

In [31]:
a.shape

(2, 2)

In [32]:
c.shape

(3, 3)

In [33]:
a + c

ValueError: operands could not be broadcast together with shapes (2,2) (3,3) 

## Matrix Multiplication

### Element-wise

In [34]:
m = np.array([[1,2,3],[4,5,6]])
m

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
n = m * 0.25
n

array([[0.25, 0.5 , 0.75],
       [1.  , 1.25, 1.5 ]])

In [36]:
m * n

array([[0.25, 1.  , 2.25],
       [4.  , 6.25, 9.  ]])

In [37]:
np.multiply(m, n)   # equivalent to m * n

array([[0.25, 1.  , 2.25],
       [4.  , 6.25, 9.  ]])

### Matrix Product

In [38]:
a = np.array([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [39]:
a.shape

(2, 4)

In [40]:
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [41]:
b.shape

(4, 3)

In [42]:
c = np.matmul(a, b)
c

array([[ 70,  80,  90],
       [158, 184, 210]])

In [43]:
c.shape

(2, 3)

### `dot` Function

It turns out that the results of `dot` and `matmul` are the same if the matrices are **two** dimensional

In [44]:
a = np.array([[1,2, 0],[3,4, 0], [5, 6, 0]])
a

array([[1, 2, 0],
       [3, 4, 0],
       [5, 6, 0]])

In [45]:
np.dot(a,a)

array([[ 7, 10,  0],
       [15, 22,  0],
       [23, 34,  0]])

In [46]:
a.dot(a)

array([[ 7, 10,  0],
       [15, 22,  0],
       [23, 34,  0]])

In [47]:
np.matmul(a,a)

array([[ 7, 10,  0],
       [15, 22,  0],
       [23, 34,  0]])

## Matrix Transposes

In [48]:
m = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
m

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [49]:
m.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [50]:
m_t = m.T
m_t

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [51]:
m_t[3][1] = 200
m_t

array([[  1,   5,   9],
       [  2,   6,  10],
       [  3,   7,  11],
       [  4, 200,  12]])

#### A change in `m_t` also changes `m`

In [52]:
m

array([[  1,   2,   3,   4],
       [  5,   6,   7, 200],
       [  9,  10,  11,  12]])

In [53]:
inputs = np.array([[-0.27,  0.45,  0.64, 0.31]])
inputs

array([[-0.27,  0.45,  0.64,  0.31]])

In [54]:
inputs.shape

(1, 4)

In [55]:
weights = np.array([[0.02, 0.001, -0.03, 0.036], \
    [0.04, -0.003, 0.025, 0.009], [0.012, -0.045, 0.28, -0.067]])
weights

array([[ 0.02 ,  0.001, -0.03 ,  0.036],
       [ 0.04 , -0.003,  0.025,  0.009],
       [ 0.012, -0.045,  0.28 , -0.067]])

In [56]:
weights.shape

(3, 4)

In [57]:
np.matmul(inputs, weights.T)

array([[-0.01299,  0.00664,  0.13494]])

In [58]:
np.matmul(weights, inputs.T)

array([[-0.01299],
       [ 0.00664],
       [ 0.13494]])